config/routes.rb
Rails.application.routes.draw do
  resources :insuarances do
  get 'insuarances',to: 'insuarances#calculate_premium', as: :calculate_premium
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "insuarances#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/insuarance.rb
class Insuarance < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/insuarances_controller.rb
class InsuarancesController < ApplicationController
  before_action :set_insuarance, only: %i[ show edit update destroy ]

  def index
    @insuarances = Insuarance.all
  end

  def show
  end

  def new
    @insuarance = Insuarance.new
  end

  def edit
  end

  def create
    @insuarance = Insuarance.new(insuarance_params)

    respond_to do |format|
      if @insuarance.save
        format.html { redirect_to insuarance_url(@insuarance), notice: "Insuarance was successfully created." }
        format.json { render :show, status: :created, location: @insuarance }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @insuarance.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @insuarance.update(insuarance_params)
        format.html { redirect_to insuarance_url(@insuarance), notice: "Insuarance was successfully updated." }
        format.json { render :show, status: :ok, location: @insuarance }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @insuarance.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @insuarance.destroy

    respond_to do |format|
      format.html { redirect_to insuarances_url, notice: "Insuarance was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def calculate_premium
    municipla_evaluation_of_property = params[:municipla_evaluation_of_property]
    prime_avant_tax = (((municipla_evaluation_of_property-50000)/1000)*1.17)+320
    emission_fees = 20
    tax = (prime_avant_tax*9)/100
    @insuarance_premium = (prime_avant_tax) + (emission_fees) + (tax)
    render json: {insuarance_premium: @insuarance_premium}
  end

  private
    def set_insuarance
      @insuarance = Insuarance.find(params[:id])
    end

    def insuarance_params
      params.require(:insuarance).permit(:first_name, :address, :last_name, :postal_code, :email, :city, :phone, :province, :municipla_evaluation_of_property, :insuarance_premium, :language, :second_home_owner, :third_home_owner, :type_of_property, :present_owner, :purchase_date, :lot_number, :bound_by_water, :ensure_municipal_water_sewer, :ensure_property, :client_knowledge, :note, :referral_agent_name, :referral_agent_email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/insuarances_helper.rb
module InsuarancesHelper
end

app/views/insuarances/_form.html.erb
<%= form_with(model: insuarance) do |form| %>
  <% if insuarance.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(insuarance.errors.count, "error") %> prohibited this insuarance from being saved:</h2>

      <ul>
        <% insuarance.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
      <td>
        <div>
          <%= form.label :first_name, style: "display: block" %>
          <%= form.text_field :first_name %>
        </div>
      </td>
      <td>
        <div>
          <%= form.label :address, style: "display: block" %>
          <%= form.text_area :address %>
        </div>
      </td>
  </tr>

  <tr>
    <td>
      <div>
        <%= form.label :last_name, style: "display: block" %>
        <%= form.text_field :last_name %>
      </div>
    </td>
    <td>
      <div>
        <%= form.label :postal_code, style: "display: block" %>
        <%= form.text_field :postal_code %>
      </div>
    </td>
  </tr>

  <tr>
    <td>
      <div>
        <%= form.label :email, style: "display: block" %>
        <%= form.text_field :email %>
      </div>
    </td>
    <td>
      <div>
        <%= form.label :city, style: "display: block" %>
        <%= form.text_field :city %>
      </div>
    </td>
  </tr>

  <tr>
    <td>
      <div>
        <%= form.label :phone, style: "display: block" %>
        <%= form.text_field :phone %>
      </div>
    </td>
    <td>
      <div>
        <%= form.label :province, style: "display: block" %>
        <%= form.text_field :province %>
      </div>
    </td>
  </tr>

  <tr>
    <td>
      <div>
        <%= form.label :municipla_evaluation_of_property, style: "display: block" %>
        <%= form.text_field :municipla_evaluation_of_property %>
      </div>
    </td>
  </tr>

  </table>
  <br>
    <div>
      <%= link_to "GET A QUOTE", "#", onclick: "showDiv()"%>
      <%# <%= link_to "GET A QUOTE", class: "premium" %>
    </div>
  <br>

  <div id="welcomeDiv"  style="display:none;" class="answer_list" >

    <div>
      <%= form.label :insuarance_premium, style: "display: block" %>
      <%= form.text_field :insuarance_premium %>
    </div>

    <h2>Transaction information</h2>
    <table>
      <tr>
        <td>
          <%= form.label :language, "Language", style: "display: block" %>
        </td>
        <td>
          <%= form.label :language, "French", style: "display: block" %>
          <%= form.radio_button :language, true %>
        </td>
        <td>
          <%= form.label :language, "English", style: "display: block" %>
          <%= form.radio_button :language, false, checked: true %>
        </td>
      </tr>
      <tr>
        <td>
          <div>
            <%= form.label :second_home_owner, style: "display: block" %>
            <%= form.text_field :second_home_owner %>
          </div>
        </td>
        <td>
          <div>
            <%= form.label :third_home_owner, style: "display: block" %>
            <%= form.text_field :third_home_owner %>
          </div>
        </td>
      </tr>
    <tr>
      <td>
        <%= form.label :type_of_property, style: "display: block" %>
        <%= form.select :type_of_property, [["Single-family Dwelling", 1], ["Condominium", 0]] %>
      </td>
    </tr>

      <div>
        <%= form.label :present_owner, "Are you presently the owner of that property ?", style: "display: block" %>
        <%= form.check_box :present_owner %>
      </div>

      <div>
        <%= form.label :purchase_date, style: "display: block" %>
        <%= form.date_field :purchase_date %>
      </div>

      <h2>Property legal description</h2>

      <div>
        <%= form.label :lot_number, style: "display: block" %>
        <%= form.number_field :lot_number %>
      </div>

      <h2>Information regarding the property</h2>

      <tr>
        <td>
          <%= form.label :bound_by_water, "Is the Insured Property bound by water (lac, stream, river, etc.)?*", style: "display: block" %>
        <td>
          <%= form.label :language, "Yes", style: "display: block" %>
          <%= form.radio_button :bound_by_water, false, checked: true %>
        <td>
          <%= form.label :language, "No", style: "display: block" %>
          <%= form.radio_button :bound_by_water, true %>
        </td>
      </tr>
      <tr>
        <td>
          <%= form.label :ensure_municipal_water_sewer, "Is the Insured Property on Municipal Water and Municipal Sewer?*", style: "display: block" %>
        <td>
          <%= form.label :language, "Yes", style: "display: block" %>
          <%= form.radio_button :ensure_municipal_water_sewer, false, checked: true %>
        <td>
          <%= form.label :language, "No", style: "display: block" %>
          <%= form.radio_button :ensure_municipal_water_sewer, true %>
        </td>
      </tr>
      <tr>
        <td>
          <%= form.label :ensure_property, "Has a title insurance already been issued for the insured property according to the client ?*", style: "display: block" %>
        <td>  
          <%= form.label :language, "Yes", style: "display: block" %>
          <%= form.radio_button :ensure_property, false, checked: true %>
        <td>
          <%= form.label :language, "No", style: "display: block" %>
          <%= form.radio_button :ensure_property, true %>
        </td>
      </tr>
      <tr>
        <td>
          <%= form.label :client_knowledge, "Has a title insurance been denied for the insured property, to the best of the client's knowledge?*", style: "display: block" %>
        <td> 
          <%= form.label :language, "Yes", style: "display: block" %>
          <%= form.radio_button :client_knowledge, false, checked: true %>
        <td>
          <%= form.label :language, "No", style: "display: block" %>
          <%= form.radio_button :client_knowledge, true %>
        </td>
      </tr>

      <div>
        <%= form.label :note, style: "display: block" %>
        <%= form.text_area :note %>
      </div>

      <div>
        <%= form.label :referral_agent_name, style: "display: block" %>
        <%= form.text_field :referral_agent_name %>
      </div>

      <div>
        <%= form.label :referral_agent_email, style: "display: block" %>
        <%= form.text_field :referral_agent_email %>
      </div>
    </table> 

    <div>
      <%= form.submit %>
    </div>
  </div>
<% end %>

<script>
  function showDiv() {
   document.getElementById('welcomeDiv').style.display = "block";
  }
  $('.premium').click(function(){
    $.ajax({
      url: '/insuarances/:insuarance_id/insuarances',
      method: 'POST',
      dataType: "script",
    format: "js",
      data: { "municipla_evaluation_of_property": municipla_evaluation_of_property },
      success: function (){
        console.log("SUCESS!!", data['head'])
      },
      error: function () {
          console.log("FAILURE");
      },
      async: true
      }); 
  });
</script>

app/views/insuarances/_insuarance.html.erb
<div id="<%= dom_id insuarance %>">
  <p>
    <strong>First name:</strong>
    <%= insuarance.first_name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= insuarance.address %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= insuarance.last_name %>
  </p>

  <p>
    <strong>Postal code:</strong>
    <%= insuarance.postal_code %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= insuarance.email %>
  </p>

  <p>
    <strong>City:</strong>
    <%= insuarance.city %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= insuarance.phone %>
  </p>

  <p>
    <strong>Province:</strong>
    <%= insuarance.province %>
  </p>

  <p>
    <strong>Municipla evaluation of property:</strong>
    <%= insuarance.municipla_evaluation_of_property %>
  </p>

  <p>
    <strong>Insuarance premium:</strong>
    <%= insuarance.insuarance_premium %>
  </p>

  <p>
    <strong>Language:</strong>
    <%= insuarance.language %>
  </p>

  <p>
    <strong>Second home owner:</strong>
    <%= insuarance.second_home_owner %>
  </p>

  <p>
    <strong>Third home owner:</strong>
    <%= insuarance.third_home_owner %>
  </p>

  <p>
    <strong>Type of property:</strong>
    <%= insuarance.type_of_property %>
  </p>

  <p>
    <strong>Present owner:</strong>
    <%= insuarance.present_owner %>
  </p>

  <p>
    <strong>Purchase date:</strong>
    <%= insuarance.purchase_date %>
  </p>

  <p>
    <strong>Lot number:</strong>
    <%= insuarance.lot_number %>
  </p>

  <p>
    <strong>Bound by water:</strong>
    <%= insuarance.bound_by_water %>
  </p>

  <p>
    <strong>Ensure municipal water sewer:</strong>
    <%= insuarance.ensure_municipal_water_sewer %>
  </p>

  <p>
    <strong>Ensure property:</strong>
    <%= insuarance.ensure_property %>
  </p>

  <p>
    <strong>Client knowledge:</strong>
    <%= insuarance.client_knowledge %>
  </p>

  <p>
    <strong>Note:</strong>
    <%= insuarance.note %>
  </p>

  <p>
    <strong>Referral agent name:</strong>
    <%= insuarance.referral_agent_name %>
  </p>

  <p>
    <strong>Referral agent email:</strong>
    <%= insuarance.referral_agent_email %>
  </p>

</div>

app/views/insuarances/edit.html.erb
<h1>Editing insuarance</h1>

<%= render "form", insuarance: @insuarance %>

<br>

<div>
  <%= link_to "Show this insuarance", @insuarance %> |
  <%= link_to "Back to insuarances", insuarances_path %>
</div>

app/views/insuarances/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Insuarances</h1>

<div id="insuarances">
  <% @insuarances.each do |insuarance| %>
    <%= render insuarance %>
    <p>
      <%= link_to "Show this insuarance", insuarance %>
    </p>
  <% end %>
</div>

<%= link_to "New insuarance", new_insuarance_path %>

app/views/insuarances/new.html.erb
<h1>Quotation Form</h1>

<%= render "form", insuarance: @insuarance %>

<br>

<div>
  <%= link_to "Back to insuarances", insuarances_path %>
</div>

app/views/insuarances/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @insuarance %>

<div>
  <%= link_to "Edit this insuarance", edit_insuarance_path(@insuarance) %> |
  <%= link_to "Back to insuarances", insuarances_path %>

  <%= button_to "Destroy this insuarance", @insuarance, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InsuaranceForm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>